# Generated by Django 5.2.14 on 2026-05-18 15:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0006_ghsa_linked_advisory"),
        ("projects", "0002_ghsa_linked_advisory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerabilityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged into advisory"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                (
                    "details",
                    models.TextField(validators=[django.core.validators.MaxLengthValidator(16384)]),
                ),
                ("affected_versions", models.CharField(blank=True, max_length=300)),
                ("reporter_name", models.CharField(blank=True, max_length=200)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                (
                    "reporter_pgp_key",
                    models.TextField(
                        blank=True, validators=[django.core.validators.MaxLengthValidator(8192)]
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "is_honeypot",
                    models.BooleanField(
                        default=False,
                        help_text="True when the hidden honeypot field was filled — never shown in triage.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_reason", models.TextField(blank=True)),
                ("pii_cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_advisory",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_report",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target project. Null = unsorted (routes to global admins).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authenticated user who submitted, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "created_at"], name="intake_vuln_state_c19984_idx"
                    ),
                    models.Index(
                        fields=["project", "state"], name="intake_vuln_project_36ea79_idx"
                    ),
                    models.Index(fields=["is_honeypot"], name="intake_vuln_is_hone_de333c_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "dismissed"), _negated=True),
                            ("dismissed_reason__gt", ""),
                            _connector="OR",
                        ),
                        name="report_dismissed_has_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "triaged"), _negated=True),
                            ("converted_advisory__isnull", False),
                            _connector="OR",
                        ),
                        name="report_triaged_has_advisory",
                    ),
                ],
            },
        ),
    ]
