# Generated by Django 5.2.14 on 2026-05-19 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intake", "0002_vulnerabilityreport_admin_routing_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoneypotSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_user_agent", models.CharField(blank=True, max_length=512)),
                ("honeypot_field_value", models.CharField(blank=True, max_length=512)),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("pii_cleared_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(fields=["submitted_at"], name="intake_hone_submitt_993bce_idx")
                ],
            },
        ),
    ]
