# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Eclipse Foundation PMI project id (e.g. 'technology.jetty').",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid Eclipse Foundation PMI project id (lowercase letters, digits, '.', '-', '_'; e.g. 'technology.jetty').",
                                regex="^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                (
                    "is_mature_publisher",
                    models.BooleanField(
                        default=False,
                        help_text="If true, members of the security team can publish advisories without top-level review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_pmi_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_pmi_sync_error", models.TextField(blank=True)),
                (
                    "security_team",
                    models.ForeignKey(
                        help_text="Group whose members are the project's security team.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects_secured",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("last_seen_in_pmi_at", models.DateTimeField()),
                ("soft_removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_repositories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["owner", "name"],
                "indexes": [
                    models.Index(fields=["owner", "name"], name="projects_pr_owner_52be26_idx"),
                    models.Index(
                        fields=["project", "soft_removed_at"], name="projects_pr_project_0c3c6b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "owner", "name"), name="project_github_repo_unique"
                    )
                ],
            },
        ),
    ]
