# Generated by Django 5.2.14 on 2026-05-14 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_pmi_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_pmi_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ProjectGitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("last_seen_in_pmi_at", models.DateTimeField()),
                ("soft_removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_repositories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["owner", "name"],
                "indexes": [
                    models.Index(fields=["owner", "name"], name="projects_pr_owner_52be26_idx"),
                    models.Index(
                        fields=["project", "soft_removed_at"], name="projects_pr_project_0c3c6b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "owner", "name"), name="project_github_repo_unique"
                    )
                ],
            },
        ),
    ]
