# Generated by Django 5.2.14 on 2026-06-03 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_unsorted_sentinel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_roster_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_roster_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SecurityTeamRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("eclipse_username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("last_seen_in_pmi_at", models.DateTimeField()),
                ("soft_removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_roster",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["eclipse_username"],
                "indexes": [
                    models.Index(
                        fields=["project", "soft_removed_at"], name="projects_se_project_531a43_idx"
                    ),
                    models.Index(fields=["email"], name="projects_se_email_26ce08_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "eclipse_username"), name="security_roster_unique"
                    )
                ],
            },
        ),
    ]
