# Generated by Django 5.2.15 on 2026-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_last_roster_sync_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgithubrepository",
            name="pvr_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectgithubrepository",
            name="pvr_enabled",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
