# Generated by Django 5.2.14 on 2026-06-11 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0004_advisoryvisit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_fingerprint",
                        to="advisories.advisory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimilarityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("candidate_pool_size", models.PositiveIntegerField(default=0)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_checks",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "enqueued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="similarity_checks",
                        to="advisories.advisoryversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("confidence", models.PositiveSmallIntegerField()),
                ("rationale", models.CharField(blank=True, max_length=500)),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "matched_advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_matches",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "check_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="similarity.similaritycheck",
                    ),
                ),
            ],
            options={
                "ordering": ["check_run", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="similaritycheck",
            index=models.Index(
                fields=["status", "created_at"], name="similarity__status_ffc0c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="similaritycheck",
            index=models.Index(
                fields=["advisory", "status"], name="similarity__advisor_61ddcd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="similaritycandidate",
            constraint=models.UniqueConstraint(
                fields=("check_run", "matched_advisory"), name="simcand_unique_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="similaritycandidate",
            constraint=models.UniqueConstraint(
                fields=("check_run", "rank"), name="simcand_unique_rank"
            ),
        ),
    ]
