# Generated by Django 5.2.14 on 2026-06-01 08:27

import advisories.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanCve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[advisories.validators.validate_cve_id],
                    ),
                ),
                ("previous_advisory_label", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("orphaned", "Orphaned (awaiting cve.org rejection)"),
                            ("marked_rejected", "Marked as rejected at cve.org"),
                            ("reassigned", "Reassigned back to advisory"),
                        ],
                        default="orphaned",
                        max_length=24,
                    ),
                ),
                ("unassigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassign_reason", models.TextField()),
                ("marked_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("marked_rejected_notes", models.TextField(blank=True)),
                (
                    "marked_rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_advisory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orphaned_cves",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "unassigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unassigned_at"],
            },
        ),
        migrations.CreateModel(
            name="OrphanCveReassignmentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("resolved_reassigned", "Resolved — CVE reattached"),
                            ("resolved_replaced", "Resolved — replaced with a new CVE"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("replacement_cve_id", models.CharField(blank=True, max_length=32)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orphan_reassignment_tasks",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "orphan_cve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reassignment_tasks",
                        to="workflows.orphancve",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_tasks",
                        to="advisories.advisoryversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CveRequestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("reserved", "Reserved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("cve_id", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_requests",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cve_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="workflows_c_status_1a0f87_idx"
                    ),
                    models.Index(
                        fields=["advisory", "status"], name="workflows_c_advisor_7128b1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "queued")),
                        fields=("advisory",),
                        name="cve_request_one_open_per_advisory",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="orphancve",
            index=models.Index(
                fields=["status", "unassigned_at"], name="workflows_o_status_9adef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orphancvereassignmenttask",
            index=models.Index(
                fields=["status", "created_at"], name="workflows_o_status_61ce91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orphancvereassignmenttask",
            index=models.Index(
                fields=["advisory", "status"], name="workflows_o_advisor_41d4a5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orphancvereassignmenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "queued")),
                fields=("orphan_cve",),
                name="orphan_reassignment_one_open_per_orphan",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["status", "created_at"], name="workflows_r_status_fde011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["advisory", "status"], name="workflows_r_advisor_02f5cc_idx"
            ),
        ),
    ]
