# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cverequesttask",
            new_name="workflows_c_status_1a0f87_idx",
            old_name="cve_status_idx",
        ),
        migrations.RenameIndex(
            model_name="cverequesttask",
            new_name="workflows_c_advisor_7128b1_idx",
            old_name="cve_adv_status_idx",
        ),
        migrations.RenameIndex(
            model_name="reviewtask",
            new_name="workflows_r_status_fde011_idx",
            old_name="rev_status_idx",
        ),
        migrations.RenameIndex(
            model_name="reviewtask",
            new_name="workflows_r_advisor_02f5cc_idx",
            old_name="rev_adv_status_idx",
        ),
        migrations.AlterField(
            model_name="cverequesttask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
