# Generated by Django 5.2.14 on 2026-05-13 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0005_assigned_cve_id_and_request_ban"),
        ("workflows", "0002_rename_cve_status_idx_workflows_c_status_1a0f87_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cverequesttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "in_progress"])),
                fields=("advisory",),
                name="cve_request_one_open_per_advisory",
            ),
        ),
    ]
