# Generated by Django 5.2.14 on 2026-05-13 22:25

import advisories.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0005_assigned_cve_id_and_request_ban"),
        ("workflows", "0003_unique_open_cve_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanCve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[advisories.validators.validate_cve_id],
                    ),
                ),
                ("previous_advisory_label", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("orphaned", "Orphaned (awaiting cve.org rejection)"),
                            ("marked_rejected", "Marked as rejected at cve.org"),
                        ],
                        default="orphaned",
                        max_length=24,
                    ),
                ),
                ("unassigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassign_reason", models.TextField()),
                ("marked_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("marked_rejected_notes", models.TextField(blank=True)),
                (
                    "marked_rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_advisory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orphaned_cves",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "unassigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unassigned_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "unassigned_at"], name="workflows_o_status_9adef9_idx"
                    )
                ],
            },
        ),
    ]
