# Generated by Django 5.2.14 on 2026-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_simplify_cve_request_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes requested"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="open",
                max_length=24,
            ),
        ),
    ]
