# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="advisorycomment",
            new_name="comments_ad_advisor_a6821f_idx",
            old_name="cmt_adv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="advisorycomment",
            new_name="comments_ad_parent__dc9006_idx",
            old_name="cmt_parent_idx",
        ),
        migrations.AlterField(
            model_name="advisorycomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
