# Generated by Django 5.2.14 on 2026-05-20 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0008_alter_advisory_state_advisoryintakemetadata"),
        ("comments", "0002_rename_cmt_adv_created_idx_comments_ad_advisor_a6821f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisorycomment",
            name="is_internal",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Visible only to collaborators and owners. Fixed at creation.",
            ),
        ),
        migrations.AddIndex(
            model_name="advisorycomment",
            index=models.Index(
                fields=["advisory", "is_internal", "created_at"],
                name="comments_ad_advisor_a62fbb_idx",
            ),
        ),
    ]
