# Generated by Django 5.2.14 on 2026-05-20 07:52
"""Add CommentVersion: append-only edit history for AdvisoryComment.

The data backfill seeds a v1 row for every existing AdvisoryComment with
its current body. Comments that were edited before this migration ran
have only their post-edit body — the pre-edit text was never stored
anywhere and cannot be recovered. The seeded v1's ``created_at`` is
aligned to the parent comment's ``created_at`` so the timeline is
plausible; this is approximate, not historically accurate, for
previously-edited rows.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_initial_versions(apps, schema_editor):
    AdvisoryComment = apps.get_model("comments", "AdvisoryComment")
    CommentVersion = apps.get_model("comments", "CommentVersion")
    seeded = []
    for c in AdvisoryComment.objects.all().iterator():
        cv = CommentVersion(comment_id=c.pk, version=1, body=c.body, editor_id=c.author_id)
        cv.save()
        seeded.append((cv.pk, c.created_at))
    # Align created_at with the parent comment (auto_now_add overrode it on insert).
    for pk, created_at in seeded:
        CommentVersion.objects.filter(pk=pk).update(created_at=created_at)


def drop_versions(apps, schema_editor):
    CommentVersion = apps.get_model("comments", "CommentVersion")
    CommentVersion.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_advisorycomment_is_internal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="comments.advisorycomment",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["comment", "version"],
                "indexes": [
                    models.Index(
                        fields=["comment", "version"], name="comments_co_comment_6849a0_idx"
                    )
                ],
                "unique_together": {("comment", "version")},
            },
        ),
        migrations.RunPython(seed_initial_versions, drop_versions),
    ]
