# Generated by Django 5.2.14 on 2026-06-01 08:27

import advisories.validators
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm must be installed before the gin_trgm_ops search indexes
        # (adv_summary_trgm / adv_details_trgm / adv_advisory_id_trgm) that
        # 0002_initial creates on advisories_advisory.
        TrigramExtension(),
        migrations.CreateModel(
            name="AdvisoryIntakeMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reporter_display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional free-text name for crediting. Never used for authorization.",
                        max_length=200,
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_user_agent", models.CharField(blank=True, max_length=512)),
                ("needs_admin_routing", models.BooleanField(db_index=True, default=False)),
                ("admin_routing_note", models.TextField(blank=True)),
                ("flagged_for_routing_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("pii_cleared_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdvisoryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["advisory", "version"],
            },
        ),
        migrations.CreateModel(
            name="Advisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "advisory_id",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[advisories.validators.validate_advisory_id],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("triage", "Triage"),
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("none", "Not submitted"),
                            ("submitted", "Submitted for review"),
                            ("changes_requested", "Changes requested"),
                            ("approved", "Approved"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("submitted_for_review_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("details", models.TextField(blank=True)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_aliases],
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_references],
                    ),
                ),
                (
                    "affected",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_affected],
                    ),
                ),
                (
                    "severity",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_severity],
                    ),
                ),
                (
                    "cwe_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_cwe_ids],
                    ),
                ),
                (
                    "credits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[advisories.validators.validate_credits],
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_reason", models.TextField(blank=True)),
                ("dismissed_reason", models.TextField(blank=True)),
                (
                    "dismissed_from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("triage", "Triage"),
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("republish_required", models.BooleanField(default=False)),
                ("access_review_required_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_cve_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[advisories.validators.validate_cve_id],
                    ),
                ),
                ("cve_requests_banned", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("native", "Native"), ("ghsa_linked", "GHSA-linked")],
                        default="native",
                        max_length=16,
                    ),
                ),
                (
                    "ghsa_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[advisories.validators.validate_ghsa_id],
                    ),
                ),
                ("ghsa_owner", models.CharField(blank=True, max_length=100)),
                ("ghsa_repo", models.CharField(blank=True, max_length=200)),
                ("ghsa_metadata", models.JSONField(blank=True, null=True)),
                ("ghsa_metadata_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ghsa_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown"),
                            ("draft", "Draft"),
                            ("triage", "Triage"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "ghsa_cve_push_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Not requested"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("ghsa_cve_push_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("ghsa_cve_conflict_detected_at", models.DateTimeField(blank=True, null=True)),
                ("ghsa_cve_conflict_ghsa_value", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
