# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advisories",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="submitted_for_review_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advisoryintakemetadata",
            name="advisory",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intake",
                to="advisories.advisory",
            ),
        ),
        migrations.AddField(
            model_name="advisoryintakemetadata",
            name="flagged_for_routing_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advisoryintakemetadata",
            name="reporter_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Set iff the submitter was authenticated. OIDC-verified identity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advisoryversion",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="advisories.advisory",
            ),
        ),
        migrations.AddField(
            model_name="advisoryversion",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["state"], name="advisories__state_73661c_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["project", "state"], name="advisories__project_73a604_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["review_status"], name="advisories__review__a1f93c_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["kind"], name="advisories__kind_1c323d_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["ghsa_id"], name="advisories__ghsa_id_cf4fbb_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["aliases"], name="adv_aliases_gin", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["summary"], name="adv_summary_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["details"], name="adv_details_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["advisory_id"], name="adv_advisory_id_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="advisory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ghsa_id__gt", "")),
                fields=("ghsa_id",),
                name="advisory_ghsa_id_unique_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryintakemetadata",
            index=models.Index(
                fields=["needs_admin_routing"], name="advisories__needs_a_86b210_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryintakemetadata",
            index=models.Index(fields=["submitted_at"], name="advisories__submitt_0d02ba_idx"),
        ),
        migrations.AddIndex(
            model_name="advisoryversion",
            index=models.Index(
                fields=["advisory", "version"], name="advisories__advisor_a0d1f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="advisoryversion",
            unique_together={("advisory", "version")},
        ),
    ]
