# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0003_advisory_access_review_required_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="advisory",
            new_name="advisories__state_73661c_idx",
            old_name="adv_state_idx",
        ),
        migrations.RenameIndex(
            model_name="advisory",
            new_name="advisories__project_73a604_idx",
            old_name="adv_proj_state_idx",
        ),
        migrations.RenameIndex(
            model_name="advisory",
            new_name="advisories__review__a1f93c_idx",
            old_name="adv_review_idx",
        ),
        migrations.RenameIndex(
            model_name="advisorysnapshot",
            new_name="advisories__advisor_556465_idx",
            old_name="adv_snap_idx",
        ),
        migrations.AlterField(
            model_name="advisory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="advisorysnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
