# Generated by Django 5.2.14 on 2026-05-13 21:46

import advisories.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0004_rename_adv_state_idx_advisories__state_73661c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="assigned_cve_id",
            field=models.CharField(
                blank=True, max_length=32, validators=[advisories.validators.validate_cve_id]
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="cve_requests_banned",
            field=models.BooleanField(default=False),
        ),
    ]
