# Generated by Django 5.2.15 on 2026-06-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0005_advisory_reassignment_request_note_and_more"),
        ("projects", "0003_project_last_roster_sync_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="reassignment_suggested_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
            ),
        ),
    ]
