# Generated by Django 5.2.14 on 2026-05-14 22:15

import advisories.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0005_assigned_cve_id_and_request_ban"),
        ("projects", "0002_ghsa_linked_advisory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="ghsa_cve_conflict_detected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_cve_conflict_ghsa_value",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_cve_push_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_cve_push_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Not requested"),
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_id",
            field=models.CharField(
                blank=True, max_length=32, validators=[advisories.validators.validate_ghsa_id]
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_metadata_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_owner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_repo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="advisory",
            name="ghsa_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unknown"),
                    ("draft", "Draft"),
                    ("triage", "Triage"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="kind",
            field=models.CharField(
                choices=[("native", "Native"), ("ghsa_linked", "GHSA-linked")],
                default="native",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["kind"], name="advisories__kind_1c323d_idx"),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(fields=["ghsa_id"], name="advisories__ghsa_id_cf4fbb_idx"),
        ),
        migrations.AddConstraint(
            model_name="advisory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ghsa_id__gt", "")),
                fields=("ghsa_id",),
                name="advisory_ghsa_id_unique_when_set",
            ),
        ),
    ]
