# Generated by Django 5.2.14 on 2026-05-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0007_advisory_no_delete_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="state",
            field=models.CharField(
                choices=[
                    ("triage", "Triage"),
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("dismissed", "Dismissed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AdvisoryIntakeMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reporter_display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional free-text name for crediting. Never used for authorization.",
                        max_length=200,
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_user_agent", models.CharField(blank=True, max_length=512)),
                ("needs_admin_routing", models.BooleanField(db_index=True, default=False)),
                ("admin_routing_note", models.TextField(blank=True)),
                ("flagged_for_routing_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("pii_cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "flagged_for_routing_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set iff the submitter was authenticated. OIDC-verified identity.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["needs_admin_routing"], name="advisories__needs_a_86b210_idx"
                    ),
                    models.Index(fields=["submitted_at"], name="advisories__submitt_0d02ba_idx"),
                ],
            },
        ),
    ]
