# Generated by Django 5.2.15 on 2026-06-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0007_advisory_withdrawal_request_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="comments_lock_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="comments_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisory",
            name="comments_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisory",
            name="comments_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
