# Generated by Django 5.2.14 on 2026-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0008_alter_advisory_state_advisoryintakemetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("none", "Not submitted"),
                    ("submitted", "Submitted for review"),
                    ("changes_requested", "Changes requested"),
                    ("approved", "Approved"),
                ],
                default="none",
                max_length=24,
            ),
        ),
    ]
