# Generated by Django 5.2.15 on 2026-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0010_advisory_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="ghsa_sync_error",
            field=models.TextField(blank=True),
        ),
    ]
