# Generated by Django 5.2.14 on 2026-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_provisioned",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for a 'shadow' account pre-provisioned from the Eclipse project security-team roster (see projects.SecurityTeamRosterEntry). Such a user has never logged in and holds NO authorization — it exists only so security-team members are reachable by notifications before their first login. Cleared on first OIDC login, after which group membership (and therefore access) comes from the OIDC claim. See INV-OIDC-5.",
            ),
        ),
    ]
