# Generated by Django 5.2.14 on 2026-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_provisioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="on_triage_event",
            field=models.BooleanField(
                default=True,
                help_text="Triage-queue activity for projects where you're on the security team — a report is submitted, promoted, dismissed, reassigned, reopened, or flagged for re-routing. Global only — no per-advisory override.",
            ),
        ),
    ]
