{{- if .Values.secrets.files.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "advisoryhub.filesSecretName" . }}
  labels:
    {{- include "advisoryhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.files.pubRepoSshKey }}
  pub-repo-ssh-key: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.secrets.files.githubAppPrivateKey }}
  github-app-private-key: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
