# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("advisory.created", "Advisory Created"),
                            ("advisory.viewed", "Advisory Viewed"),
                            ("advisory.edited", "Advisory Edited"),
                            ("advisory.state_changed", "Advisory State Changed"),
                            ("advisory.project_changed", "Advisory Project Changed"),
                            (
                                "advisory.access_review_dismissed",
                                "Advisory Access Review Dismissed",
                            ),
                            ("advisory.submitted_for_review", "Advisory Submitted For Review"),
                            ("advisory.review_approved", "Advisory Review Approved"),
                            (
                                "advisory.review_changes_requested",
                                "Advisory Review Changes Requested",
                            ),
                            (
                                "advisory.review_approval_invalidated",
                                "Advisory Review Approval Invalidated",
                            ),
                            (
                                "advisory.review_approval_revoked",
                                "Advisory Review Approval Revoked",
                            ),
                            ("advisory.review_withdrawn", "Advisory Review Withdrawn"),
                            ("advisory.published", "Advisory Published"),
                            ("advisory.dismissed", "Advisory Dismissed"),
                            ("advisory.reopened", "Advisory Reopened"),
                            ("access.granted", "Access Granted"),
                            ("access.revoked", "Access Revoked"),
                            ("invitation.created", "Invitation Created"),
                            ("invitation.redeemed", "Invitation Redeemed"),
                            ("invitation.revoked", "Invitation Revoked"),
                            ("comment.created", "Comment Created"),
                            ("comment.edited", "Comment Edited"),
                            ("comment.redacted", "Comment Redacted"),
                            ("cve.requested", "Cve Requested"),
                            ("cve.task_status_changed", "Cve Task Status Changed"),
                            ("cve.request_banned", "Cve Request Banned"),
                            ("cve.request_cancelled", "Cve Request Cancelled"),
                            ("cve.unassigned", "Cve Unassigned"),
                            ("cve.marked_rejected_at_cve_org", "Cve Marked Rejected At Cve Org"),
                            ("cve.reassigned_from_orphan", "Cve Reassigned From Orphan"),
                            ("cve.orphan_reassignment_requested", "Orphan Reassignment Requested"),
                            ("cve.orphan_reassignment_resolved", "Orphan Reassignment Resolved"),
                            ("review.task_status_changed", "Review Task Status Changed"),
                            ("publication.export_started", "Publication Export Started"),
                            ("publication.export_completed", "Publication Export Completed"),
                            ("publication.export_failed", "Publication Export Failed"),
                            ("publication.osv_generated", "Publication Osv Generated"),
                            ("publication.csaf_generated", "Publication Csaf Generated"),
                            ("publication.cve_generated", "Publication Cve Generated"),
                            ("publication.git_commit", "Publication Git Commit"),
                            ("publication.git_push", "Publication Git Push"),
                            ("publication.git_push_failed", "Publication Git Push Failed"),
                            ("notification.prefs_changed", "Notification Prefs Changed"),
                            ("ghsa.metadata_fetched", "Ghsa Metadata Fetched"),
                            ("ghsa.linked_advisory_created", "Ghsa Linked Advisory Created"),
                            ("ghsa.cve_push_requested", "Ghsa Cve Push Requested"),
                            ("ghsa.cve_push_succeeded", "Ghsa Cve Push Succeeded"),
                            ("ghsa.cve_push_failed", "Ghsa Cve Push Failed"),
                            ("ghsa.cve_conflict_detected", "Ghsa Cve Conflict Detected"),
                            ("ghsa.sync_run_started", "Ghsa Sync Run Started"),
                            ("ghsa.sync_run_finished", "Ghsa Sync Run Finished"),
                            ("ghsa.installation_registered", "Ghsa Installation Registered"),
                            ("ghsa.installation_suspended", "Ghsa Installation Suspended"),
                            ("ghsa.installation_removed", "Ghsa Installation Removed"),
                            ("ghsa.webhook_received", "Ghsa Webhook Received"),
                            ("ghsa.webhook_rejected", "Ghsa Webhook Rejected"),
                            ("pmi.project_repos_synced", "Pmi Project Repos Synced"),
                            ("maintenance.enabled", "Maintenance Enabled"),
                            ("maintenance.disabled", "Maintenance Disabled"),
                            ("advisory.triage_submitted", "Advisory Triage Submitted"),
                            ("advisory.triage_promoted", "Advisory Triage Promoted"),
                            ("advisory.flagged_for_routing", "Advisory Flagged For Routing"),
                            ("advisory.routing_flag_cleared", "Advisory Routing Flag Cleared"),
                            ("report.submitted", "Report Submitted"),
                            ("report.triaged_into_advisory", "Report Triaged Into Advisory"),
                            ("report.dismissed", "Report Dismissed"),
                            ("report.project_reassigned", "Report Project Reassigned"),
                            ("report.flagged_for_routing", "Report Flagged For Routing"),
                        ],
                        max_length=64,
                    ),
                ),
                ("comment_id", models.BigIntegerField(blank=True, null=True)),
                ("previous_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="advisories.advisory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="audit_audit_created_3e5798_idx"),
                    models.Index(
                        fields=["advisory", "created_at"], name="audit_audit_advisor_11659e_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="audit_audit_actor_i_d8a8b1_idx"
                    ),
                    models.Index(fields=["action"], name="audit_audit_action_cb1e44_idx"),
                ],
            },
        ),
    ]
