"""Create the partitioned ``AccessLogEntry`` table.

``AccessLogEntry`` is the retention-managed sibling of ``AuditLogEntry`` (see
the model docstring and INV-AUDIT-5). The physical table is **range-partitioned
by month on ``created_at``** so retention is a ``DROP PARTITION`` rather than a
per-row ``DELETE``. Django's ORM cannot express ``PARTITION BY`` (nor the
composite ``(id, created_at)`` PK that Postgres requires for a partitioned
table), so this migration splits the two concerns with
``SeparateDatabaseAndState``:

* ``state_operations`` — the ordinary ``CreateModel`` Django generated from the
  model. This is what ``makemigrations --check`` compares against, so the check
  stays green and future autodetector diffs work normally.
* ``database_operations`` — hand-written DDL that creates the partitioned table
  for real. The column/FK/index definitions are copied verbatim from
  ``manage.py sqlmigrate audit 0003`` (the plain-table form), with three edits:
  the PK becomes ``(id, created_at)``, the table gains ``PARTITION BY RANGE
  (created_at)``, and a DEFAULT plus the current/next month partitions are
  created up front (so day-one inserts never land in DEFAULT — see
  ``audit/partitions.py`` for the same pitfall handling at runtime).

WARNING to future editors: the live table is partitioned. Adding a column is
fine (``ALTER TABLE ADD COLUMN`` propagates to partitions), but any new index or
unique/PK constraint must be compatible with the ``created_at`` partition key
and should be reviewed against this raw DDL, not just the model.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from audit.models import Action

# Static DDL — faithful copy of the plain-table SQL Django emits, with the PK
# made composite and the table declared partitioned. FK constraint / index
# names match Django's generated names so the live schema is indistinguishable
# from a Django-managed table aside from the partitioning.
CREATE_PARTITIONED = r"""
CREATE TABLE "audit_accesslogentry" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "action" varchar(64) NOT NULL,
    "metadata" jsonb NOT NULL,
    "ip_address" inet NULL,
    "user_agent" varchar(512) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "actor_id" bigint NULL,
    "advisory_id" bigint NULL,
    PRIMARY KEY ("id", "created_at")
) PARTITION BY RANGE ("created_at");

ALTER TABLE "audit_accesslogentry"
    ADD CONSTRAINT "audit_accesslogentry_actor_id_6cd72ebe_fk_accounts_user_id"
    FOREIGN KEY ("actor_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "audit_accesslogentry"
    ADD CONSTRAINT "audit_accesslogentry_advisory_id_76bef06c_fk_advisorie"
    FOREIGN KEY ("advisory_id") REFERENCES "advisories_advisory" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "audit_accesslogentry_actor_id_6cd72ebe" ON "audit_accesslogentry" ("actor_id");
CREATE INDEX "audit_accesslogentry_advisory_id_76bef06c" ON "audit_accesslogentry" ("advisory_id");
CREATE INDEX "acclog_created_idx" ON "audit_accesslogentry" ("created_at");
CREATE INDEX "acclog_adv_created_idx" ON "audit_accesslogentry" ("advisory_id", "created_at");
CREATE INDEX "acclog_actor_created_idx" ON "audit_accesslogentry" ("actor_id", "created_at");
CREATE INDEX "acclog_action_idx" ON "audit_accesslogentry" ("action");

CREATE TABLE "audit_accesslogentry_default" PARTITION OF "audit_accesslogentry" DEFAULT;
"""

DROP_PARTITIONED = 'DROP TABLE IF EXISTS "audit_accesslogentry" CASCADE;'


def _create_initial_partitions(apps, schema_editor):
    """Create this month's and next month's partitions.

    Doing this in the migration (before any row exists) guarantees the
    common range is covered by a concrete partition rather than DEFAULT,
    so the runtime maintenance task can keep extending the calendar without
    hitting the "row in DEFAULT" conflict.
    """
    from datetime import date

    from django.utils import timezone

    now = timezone.now()

    def month_bounds(year, month):
        start = date(year, month, 1)
        if month == 12:
            end = date(year + 1, 1, 1)
        else:
            end = date(year, month + 1, 1)
        return start, end

    months = [(now.year, now.month)]
    months.append((now.year + 1, 1) if now.month == 12 else (now.year, now.month + 1))

    with schema_editor.connection.cursor() as cur:
        for year, month in months:
            start, end = month_bounds(year, month)
            name = f"audit_accesslogentry_p{year:04d}_{month:02d}"
            cur.execute(
                f'CREATE TABLE IF NOT EXISTS "{name}" '
                f'PARTITION OF "audit_accesslogentry" '
                f"FOR VALUES FROM ('{start.isoformat()}') TO ('{end.isoformat()}');"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0003_advisory_no_delete_trigger"),
        ("audit", "0002_append_only_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AccessLogEntry",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("action", models.CharField(choices=Action.choices, max_length=64)),
                        ("metadata", models.JSONField(blank=True, default=dict)),
                        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                        ("user_agent", models.CharField(blank=True, max_length=512)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "actor",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "advisory",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="access_log_entries",
                                to="advisories.advisory",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "indexes": [
                            models.Index(fields=["created_at"], name="acclog_created_idx"),
                            models.Index(
                                fields=["advisory", "created_at"], name="acclog_adv_created_idx"
                            ),
                            models.Index(
                                fields=["actor", "created_at"], name="acclog_actor_created_idx"
                            ),
                            models.Index(fields=["action"], name="acclog_action_idx"),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=CREATE_PARTITIONED, reverse_sql=DROP_PARTITIONED),
                migrations.RunPython(
                    _create_initial_partitions, reverse_code=migrations.RunPython.noop
                ),
            ],
        ),
    ]
