# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_action_invitation_revoked"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_audit_created_3e5798_idx",
            old_name="audit_audit_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_audit_advisor_11659e_idx",
            old_name="audit_audit_adv_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_audit_actor_i_d8a8b1_idx",
            old_name="audit_audit_actor_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_audit_action_cb1e44_idx",
            old_name="audit_audit_action_idx",
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("advisory.created", "Advisory Created"),
                    ("advisory.viewed", "Advisory Viewed"),
                    ("advisory.edited", "Advisory Edited"),
                    ("advisory.state_changed", "Advisory State Changed"),
                    ("advisory.project_changed", "Advisory Project Changed"),
                    ("advisory.access_review_dismissed", "Advisory Access Review Dismissed"),
                    ("advisory.submitted_for_review", "Advisory Submitted For Review"),
                    ("advisory.review_approved", "Advisory Review Approved"),
                    ("advisory.review_rejected", "Advisory Review Rejected"),
                    ("advisory.review_changes_requested", "Advisory Review Changes Requested"),
                    ("advisory.published", "Advisory Published"),
                    ("advisory.dismissed", "Advisory Dismissed"),
                    ("access.granted", "Access Granted"),
                    ("access.revoked", "Access Revoked"),
                    ("invitation.created", "Invitation Created"),
                    ("invitation.redeemed", "Invitation Redeemed"),
                    ("invitation.revoked", "Invitation Revoked"),
                    ("comment.created", "Comment Created"),
                    ("comment.edited", "Comment Edited"),
                    ("comment.redacted", "Comment Redacted"),
                    ("cve.requested", "Cve Requested"),
                    ("cve.task_status_changed", "Cve Task Status Changed"),
                    ("review.task_status_changed", "Review Task Status Changed"),
                    ("publication.export_started", "Publication Export Started"),
                    ("publication.export_completed", "Publication Export Completed"),
                    ("publication.export_failed", "Publication Export Failed"),
                    ("publication.osv_generated", "Publication Osv Generated"),
                    ("publication.csaf_generated", "Publication Csaf Generated"),
                    ("publication.git_commit", "Publication Git Commit"),
                    ("publication.git_push", "Publication Git Push"),
                    ("publication.git_push_failed", "Publication Git Push Failed"),
                    ("notification.prefs_changed", "Notification Prefs Changed"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
