# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="publicationtask",
            new_name="publication_status_ddceed_idx",
            old_name="pub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="publicationtask",
            new_name="publication_advisor_ebfe30_idx",
            old_name="pub_adv_status_idx",
        ),
        migrations.AlterField(
            model_name="publicationartifact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="publicationrepositoryconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="publicationtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
