# Generated by Django 5.2.14 on 2026-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0003_publicationtask_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationrepositoryconfig",
            name="cve_path_template",
            field=models.CharField(default="cves/{year}/{bucket}/{cve_id}.json", max_length=255),
        ),
        migrations.AlterField(
            model_name="publicationartifact",
            name="kind",
            field=models.CharField(
                choices=[("osv", "OSV"), ("csaf", "CSAF"), ("cve", "CVE")], max_length=8
            ),
        ),
    ]
