# Generated by Django 5.2.14 on 2026-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0004_publicationrepositoryconfig_cve_path_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationrepositoryconfig",
            name="csaf_path_template",
            field=models.CharField(default="csaf/{year}/{advisory_id}.json", max_length=255),
        ),
        migrations.AlterField(
            model_name="publicationrepositoryconfig",
            name="osv_path_template",
            field=models.CharField(default="osv/{year}/{advisory_id}.json", max_length=255),
        ),
    ]
