# Generated by Django 5.2.14 on 2026-06-01 08:27

import access.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvisoryAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "principal_type",
                    models.CharField(choices=[("user", "User"), ("group", "Group")], max_length=8),
                ),
                ("principal_id", models.BigIntegerField()),
                (
                    "permission",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("collaborator", "Collaborator")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PendingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "permission",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("collaborator", "Collaborator")],
                        max_length=16,
                    ),
                ),
                (
                    "token",
                    models.CharField(default=access.models._make_token, max_length=64, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=access.models._default_invitation_expiry),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
