# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("advisories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryaccessgrant",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to="advisories.advisory",
            ),
        ),
        migrations.AddField(
            model_name="advisoryaccessgrant",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendinginvitation",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_invitations",
                to="advisories.advisory",
            ),
        ),
        migrations.AddField(
            model_name="pendinginvitation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendinginvitation",
            name="redeemed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryaccessgrant",
            index=models.Index(
                fields=["principal_type", "principal_id"], name="access_advi_princip_689446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryaccessgrant",
            index=models.Index(
                fields=["advisory", "permission"], name="access_advi_advisor_d8a62a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="advisoryaccessgrant",
            unique_together={("advisory", "principal_type", "principal_id")},
        ),
        migrations.AddIndex(
            model_name="pendinginvitation",
            index=models.Index(fields=["email"], name="access_pend_email_002cc6_idx"),
        ),
        migrations.AddIndex(
            model_name="pendinginvitation",
            index=models.Index(
                fields=["advisory", "redeemed_at"], name="access_pend_advisor_4d185c_idx"
            ),
        ),
    ]
