# Generated by Django 5.2.14 on 2026-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="advisoryaccessgrant",
            new_name="access_advi_princip_689446_idx",
            old_name="access_principal_idx",
        ),
        migrations.RenameIndex(
            model_name="advisoryaccessgrant",
            new_name="access_advi_advisor_d8a62a_idx",
            old_name="access_adv_perm_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinginvitation",
            new_name="access_pend_email_002cc6_idx",
            old_name="invite_email_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinginvitation",
            new_name="access_pend_advisor_4d185c_idx",
            old_name="invite_adv_redeemed_idx",
        ),
        migrations.AlterField(
            model_name="advisoryaccessgrant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pendinginvitation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
