# Generated by Django 5.2.14 on 2026-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ghsa", "0001_ghsa_linked_advisory"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAppInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=100, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Organization", "Organization"), ("User", "User")],
                        default="Organization",
                        max_length=16,
                    ),
                ),
                ("app_slug", models.CharField(blank=True, max_length=100)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["account_login"],
                "indexes": [
                    models.Index(fields=["suspended_at"], name="ghsa_github_suspend_200cd7_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delivery_id", models.CharField(max_length=64, unique=True)),
                ("event", models.CharField(max_length=64)),
                ("action", models.CharField(blank=True, max_length=64)),
                ("installation_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["event", "action"], name="ghsa_webhoo_event_a07417_idx"),
                    models.Index(
                        fields=["status", "received_at"], name="ghsa_webhoo_status_523008_idx"
                    ),
                ],
            },
        ),
    ]
