# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ghsa", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ghsasyncrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ghsa_sync_runs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="ghsasyncrun",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="githubappinstallation",
            index=models.Index(fields=["suspended_at"], name="ghsa_github_suspend_200cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event", "action"], name="ghsa_webhoo_event_a07417_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "received_at"], name="ghsa_webhoo_status_523008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ghsacvepushtask",
            index=models.Index(
                fields=["status", "created_at"], name="ghsa_ghsacv_status_779d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ghsacvepushtask",
            index=models.Index(
                fields=["advisory", "status"], name="ghsa_ghsacv_advisor_d0bc00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ghsasyncrun",
            index=models.Index(fields=["scope", "started_at"], name="ghsa_ghsasy_scope_aabcd8_idx"),
        ),
        migrations.AddIndex(
            model_name="ghsasyncrun",
            index=models.Index(
                fields=["project", "started_at"], name="ghsa_ghsasy_project_8f91c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ghsasyncrun",
            index=models.Index(fields=["status"], name="ghsa_ghsasy_status_979a4d_idx"),
        ),
    ]
