# Generated by Django 5.2.14 on 2026-06-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advisories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "on_advisory_submitted_for_review",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("on_advisory_published", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "on_publication_export_status",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "comments_level",
                    models.CharField(
                        blank=True,
                        choices=[("all", "Every comment"), ("mentioned", "Only when mentioned")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisory_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["advisory"], name="adv_notif_pref_adv_idx")],
                "unique_together": {("user", "advisory")},
            },
        ),
    ]
