# Generated by Django 5.2.14 on 2026-06-05 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0004_advisoryvisit"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("advisory_created", "Advisory created"),
                            ("advisory_submitted_for_review", "Submitted for review"),
                            ("advisory_published", "Published"),
                            ("publication_export_status", "Publication status"),
                            ("comment", "New comment"),
                            ("mention", "Mention"),
                            ("triage", "Triage activity"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment_id", models.BigIntegerField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "read_at"], name="notif_recipient_read_idx"),
                    models.Index(
                        fields=["recipient", "-created_at"], name="notif_recipient_created_idx"
                    ),
                    models.Index(
                        fields=["recipient", "advisory", "read_at"], name="notif_recipient_adv_idx"
                    ),
                ],
            },
        ),
    ]
