from __future__ import annotations

import pytest
from django.core.exceptions import ValidationError
from django.db import connection, transaction

from advisories.models import (
    Advisory,
    AdvisoryVersion,
    ReviewStatus,
    State,
    _unsafe_dev_reset_bypass,
    _unsafe_dev_reset_delete_queryset,
)
from advisories.services import record_advisory_version


@pytest.mark.django_db
def test_advisory_id_autogenerated_on_save(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)
    assert advisory.advisory_id.startswith("ECL-")


@pytest.mark.django_db
def test_invalid_advisory_id_rejected_on_full_clean(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory(advisory_id="not-valid", project=project)
    with pytest.raises(ValidationError):
        advisory.full_clean()


@pytest.mark.django_db
def test_clean_requires_dismissed_reason(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)
    advisory.state = State.DISMISSED
    with pytest.raises(ValidationError):
        advisory.clean()
    advisory.dismissed_reason = "duplicate of ECL-cccc-ffff-gggg"
    advisory.clean()


@pytest.mark.django_db
def test_aliases_validator_rejects_non_list(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory(project=project, aliases={"oops": True})
    with pytest.raises(ValidationError):
        advisory.full_clean()


@pytest.mark.django_db
def test_creating_an_advisory_seeds_v1(make_project, make_user):
    user = make_user(email="alice@example.org")
    project = make_project("eclipse-jetty", team_members=[user])
    advisory = Advisory.objects.create(project=project, summary="initial", created_by=user)

    v1 = advisory.versions.get(version=1)
    assert v1.payload["summary"] == "initial"
    assert v1.editor == user


@pytest.mark.django_db
def test_version_payload_freezes_against_later_edits(make_project, make_user):
    user = make_user(email="alice@example.org")
    project = make_project("eclipse-jetty", team_members=[user])
    advisory = Advisory.objects.create(project=project, summary="initial", created_by=user)
    v1 = advisory.versions.get(version=1)

    advisory.summary = "edited"
    advisory.save()

    v1.refresh_from_db()
    assert v1.payload["summary"] == "initial"


@pytest.mark.django_db
def test_existing_version_cannot_be_saved(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project, summary="x")
    v1 = advisory.versions.get(version=1)
    v1.payload = {"summary": "tampered"}
    with pytest.raises(PermissionError):
        v1.save()


@pytest.mark.django_db
def test_version_cannot_be_deleted(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)
    v1 = advisory.versions.get(version=1)
    with pytest.raises(PermissionError):
        v1.delete()


@pytest.mark.django_db
def test_record_advisory_version_appends_next(make_project, make_user):
    user = make_user(email="alice@example.org")
    project = make_project("eclipse-jetty", team_members=[user])
    advisory = Advisory.objects.create(project=project, summary="v1", created_by=user)

    advisory.summary = "v2"
    advisory.save()
    record_advisory_version(advisory, editor=user)

    versions = list(advisory.versions.order_by("version"))
    assert [v.version for v in versions] == [1, 2]
    assert versions[0].payload["summary"] == "v1"
    assert versions[1].payload["summary"] == "v2"
    assert versions[1].editor == user


@pytest.mark.django_db
def test_record_advisory_version_if_changed_skips_no_op(make_project, make_user):
    user = make_user(email="alice@example.org")
    project = make_project("eclipse-jetty", team_members=[user])
    advisory = Advisory.objects.create(project=project, summary="stable", created_by=user)

    appended = record_advisory_version(advisory, editor=user, if_changed=True)
    assert appended is None
    assert AdvisoryVersion.objects.filter(advisory=advisory).count() == 1


@pytest.mark.django_db
def test_advisory_default_review_status(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)
    assert advisory.review_status == ReviewStatus.NONE


@pytest.mark.django_db
def test_advisory_instance_delete_blocked(make_project):
    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)
    with pytest.raises(PermissionError):
        advisory.delete()
    assert Advisory.objects.filter(pk=advisory.pk).exists()


@pytest.mark.django_db
def test_advisory_queryset_delete_blocked(make_project):
    project = make_project("eclipse-jetty")
    Advisory.objects.create(project=project)
    with pytest.raises(PermissionError):
        Advisory.objects.all().delete()
    assert Advisory.objects.exists()


@pytest.mark.django_db(transaction=True)
def test_database_trigger_blocks_raw_delete(make_project):
    """Even raw SQL through the Django connection must be rejected."""
    if connection.vendor != "postgresql":
        pytest.skip("Append-only triggers are Postgres-specific")

    project = make_project("eclipse-jetty")
    advisory = Advisory.objects.create(project=project)

    with pytest.raises(Exception) as exc:
        with transaction.atomic():
            with connection.cursor() as cur:
                cur.execute(
                    "DELETE FROM advisories_advisory WHERE id = %s",
                    [advisory.pk],
                )
    assert "non-deletable" in str(exc.value).lower() or "delete forbidden" in str(exc.value).lower()


def test_advisory_admin_forbids_delete():
    from django.contrib.admin.sites import AdminSite
    from django.test import RequestFactory

    from advisories.admin import AdvisoryAdmin

    site_admin = AdvisoryAdmin(Advisory, AdminSite())
    request = RequestFactory().get("/admin/advisories/advisory/")
    assert site_admin.has_delete_permission(request) is False
    assert "delete_selected" not in site_admin.get_actions(request)


@pytest.mark.django_db(transaction=True)
def test_unsafe_dev_reset_bypass_actually_deletes(make_project):
    """The dev-only escape hatch must succeed at removing rows."""
    project = make_project("eclipse-jetty")
    Advisory.objects.create(project=project)
    Advisory.objects.create(project=project)
    assert Advisory.objects.count() == 2

    with transaction.atomic(), _unsafe_dev_reset_bypass():
        _unsafe_dev_reset_delete_queryset(Advisory.objects.all())

    assert Advisory.objects.count() == 0
